name: cryptoutils
version: 0.5.0
author: Steven Roose <stevenroose@gmail.com>
description: A crypto utility library.
homepage: https://github.com/stevenroose/dart-cryptoutils
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ">=1.1.1 <2.0.0"

dev_dependencies:
  test: ">=1.16.2 <2.0.0"
